name: chargers

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: chargers
    ports:
      - "5432:5432" # Expose port for local debugging (optional, generally not needed for app)


  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: chargers
      RAILS_MASTER_KEY: 62e413bf3ae35ab92bb40df9c2a62155
    user: "1000:1000"

volumes:
  postgres_data:
